/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.ts to modify the generation of this file.




import * as BookYourDreamFlight from 'src/components/BookYourDreamFlight';
import * as ChooseMeal from 'src/components/ChooseMeal';
import * as CityBanner from 'src/components/CityBanner';
import * as CityList from 'src/components/CityList';
import * as ColumnSplitter from 'src/components/ColumnSplitter';
import * as CommonHeadBanner from 'src/components/CommonHeadBanner';
import * as Container from 'src/components/Container';
import * as ContentBlock from 'src/components/ContentBlock';
import * as CorporateTeam from 'src/components/CorporateTeam';
import * as Departments from 'src/components/Departments';
import * as ExperiencePageBanner from 'src/components/ExperiencePageBanner';
import * as FAQs from 'src/components/FAQs';
import * as FEaaSWrapper from 'src/components/FEaaSWrapper';
import * as Footer from 'src/components/Footer';
import * as FurtherInformationContact from 'src/components/FurtherInformationContact';
import * as GetThereWithBeond from 'src/components/GetThereWithBeond';
import * as Heading from 'src/components/Heading';
import * as HomepageBanner from 'src/components/HomepageBanner';
import * as HomepageDetails from 'src/components/HomepageDetails';
import * as HomepageHotels from 'src/components/HomepageHotels';
import * as HotelList from 'src/components/HotelList';
import * as HowWeAreSustainable from 'src/components/HowWeAreSustainable';
import * as Image from 'src/components/Image';
import * as JourneyDetails from 'src/components/JourneyDetails';
import * as JourneyDetailsSustainability from 'src/components/JourneyDetailsSustainability';
import * as JourneyDetailsWhyBeond from 'src/components/JourneyDetailsWhyBeond';
import * as LinkList from 'src/components/LinkList';
import * as Locations from 'src/components/Locations';
import * as ManagementTeam from 'src/components/ManagementTeam';
import * as MyFamily from 'src/components/MyFamily';
import * as Navigation from 'src/components/Navigation';
import * as NeedToGetInTouch from 'src/components/NeedToGetInTouch';
import * as NewsDetails from 'src/components/NewsDetails';
import * as NewsList from 'src/components/NewsList';
import * as PageContent from 'src/components/PageContent';
import * as PartialDesignDynamicPlaceholder from 'src/components/PartialDesignDynamicPlaceholder';
import * as PartnersList from 'src/components/PartnersList';
import * as PrivacyAndPolicy from 'src/components/PrivacyAndPolicy';
import * as Promo from 'src/components/Promo';
import * as RichText from 'src/components/RichText';
import * as RouteMap from 'src/components/RouteMap';
import * as RowSplitter from 'src/components/RowSplitter';
import * as Support from 'src/components/Support';
import * as Sustainability from 'src/components/Sustainability';
import * as Title from 'src/components/Title';
import * as WayToTravel from 'src/components/WayToTravel';
import * as AllBooking from 'src/components/AllBooking/AllBooking';
import * as AllBookingDetails from 'src/components/AllBooking/Tabs/AllBookingDetails';
import * as ApiUrl from 'src/components/Api/ApiUrl';
import * as BoardingPasses from 'src/components/BoardingPasses/BoardingPasses';
import * as BoardingPassesDetails from 'src/components/BoardingPasses/Tabs/BoardingPassesDetails';
import * as BookingComplete from 'src/components/BookingComplete/BookingComplete';
import * as CancelBooking from 'src/components/CancelBooking/CancelBooking';
import * as CancelSuccess from 'src/components/CancelSuccess/CancelSuccess';
import * as ChangeDate from 'src/components/ChangeDate/ChangeDate';
import * as CheckIn from 'src/components/CheckIn/CheckIn';
import * as ChooseSeats from 'src/components/ChooseSeats/ChooseSeats';
import * as CompareFareFamilies from 'src/components/CompareFareFamilies/CompareFareFamilies';
import * as CreateAccount from 'src/components/CreateAccount/CreateAccount';
import * as Debounce from 'src/components/Debounce/Debounce';
import * as EmergencyContactDetails from 'src/components/EmergencyContactDetails/EmergencyContactDetails';
import * as EmergenCycontactUser from 'src/components/EmergencyContactDetails/Tabs/EmergenCycontactUser';
import * as FindBooking from 'src/components/FindBooking/FindBooking';
import * as FlightAvailability from 'src/components/FlightAvailability/FlightAvailability';
import * as Bliss from 'src/components/FlightAvailability/Tabs/Bliss';
import * as Delight from 'src/components/FlightAvailability/Tabs/Delight';
import * as FlightInfo from 'src/components/FlightAvailability/Tabs/FlightInfo';
import * as MatrixFunctions from 'src/components/FlightAvailability/Tabs/MatrixFunctions';
import * as Opulence from 'src/components/FlightAvailability/Tabs/Opulence';
import * as Header from 'src/components/Header/Header';
import * as LandingPageSearch from 'src/components/LandingPageSearch/LandingPageSearch';
import * as Layout from 'src/components/Layout/Layout';
import * as CancelBookingLoader from 'src/components/Loader/CancelBookingLoader';
import * as FindYourBooking from 'src/components/Loader/FindYourBooking';
import * as GettingData from 'src/components/Loader/GettingData';
import * as PaymentGateway from 'src/components/Loader/PaymentGateway';
import * as SavingData from 'src/components/Loader/SavingData';
import * as SavingExpLoader from 'src/components/Loader/SavingExpLoader';
import * as SearchFlightLoader from 'src/components/Loader/SearchFlightLoader';
import * as SearchSeat from 'src/components/Loader/SearchSeat';
import * as SignInLoader from 'src/components/Loader/SignInLoader';
import * as AdultAgeModal from 'src/components/Modal/AdultAgeModal';
import * as CancelBookingModal from 'src/components/Modal/CancelBookingModal';
import * as CookiesModal from 'src/components/Modal/CookiesModal';
import * as DateOfBirthModal from 'src/components/Modal/DateOfBirthModal';
import * as DepartReturnDateModal from 'src/components/Modal/DepartReturnDateModal';
import * as DropdownModal from 'src/components/Modal/DropdownModal';
import * as EmergencyExitSeatModal from 'src/components/Modal/EmergencyExitSeatModal';
import * as FareBaggageModal from 'src/components/Modal/FareBaggageModal';
import * as ModifyBookingDetailsModal from 'src/components/Modal/ModifyBookingDetailsModal';
import * as ModifyBookingModal from 'src/components/Modal/ModifyBookingModal';
import * as NoOptionFound from 'src/components/Modal/NoOptionFound';
import * as PassengeRemoveModal from 'src/components/Modal/PassengeRemoveModal';
import * as PassengerCount from 'src/components/Modal/PassengerCount';
import * as PromoCodeModal from 'src/components/Modal/PromoCodeModal';
import * as SelectSeatLaterModal from 'src/components/Modal/SelectSeatLaterModal';
import * as YoungAgeModal from 'src/components/Modal/YoungAgeModal';
import * as AnicillaryCodeForAddons from 'src/components/ModifyBooking/AnicillaryCodeForAddons';
import * as FeaturedAddOns from 'src/components/ModifyBooking/FeaturedAddOns';
import * as ModifyBooking from 'src/components/ModifyBooking/ModifyBooking';
import * as MyFamilyDetails from 'src/components/MyFamily/MyFamilyDetails';
import * as familyFields from 'src/components/MyFamily/familyFields';
import * as MyProfile from 'src/components/MyProfile/MyProfile';
import * as NoFlight from 'src/components/NoFlight/NoFlight';
import * as CalculateDob from 'src/components/PassengerDetails/CalculateDob';
import * as FieldsData from 'src/components/PassengerDetails/FieldsData';
import * as PassengerDetails from 'src/components/PassengerDetails/PassengerDetails';
import * as PaymentCancel from 'src/components/PaymentCancel/PaymentCancel';
import * as PaymentProcess from 'src/components/PaymentProcess/PaymentProcess';
import * as ReviewChange from 'src/components/ReviewChange/ReviewChange';
import * as CodesInCurve from 'src/components/ReviewTrip/CodesInCurve';
import * as FlightSchedule from 'src/components/ReviewTrip/FlightSchedule';
import * as GetDate from 'src/components/ReviewTrip/GetDate';
import * as ModifyPassengerSeatFareFamily from 'src/components/ReviewTrip/ModifyPassengerSeatFareFamily';
import * as PriceBreakDown from 'src/components/ReviewTrip/PriceBreakDown';
import * as ReviewTrip from 'src/components/ReviewTrip/ReviewTrip';
import * as ReviewTripComplete from 'src/components/ReviewTripComplete/ReviewTripComplete';
import * as CountryData from 'src/components/SearchFlight/CountryData';
import * as SearchFlight from 'src/components/SearchFlight/SearchFlight';
import * as SitecoreContent from 'src/components/SearchFlight/SitecoreContent';
import * as StepsInfo from 'src/components/SearchFlight/StepsInfo';
import * as LandingPageOnewaySearchBar from 'src/components/SearchFlight/Tabs/LandingPageOnewaySearchBar';
import * as LandingPageSearchBar from 'src/components/SearchFlight/Tabs/LandingPageSearchBar';
import * as OnewayTab from 'src/components/SearchFlight/Tabs/OnewayTab';
import * as ReturnTab from 'src/components/SearchFlight/Tabs/ReturnTab';
import * as SelectOptions from 'src/components/Select/SelectOptions';
import * as SignIn from 'src/components/SignIn/SignIn';
import * as TermsConditions from 'src/components/TermsConditions/TermsConditions';
import * as ErrorMessages from 'src/components/Toaster/ErrorMessages';
import * as UpcomingTrip from 'src/components/UpcomingTrip/UpcomingTrip';
import * as YourCart from 'src/components/YourCart/YourCart';

const components = new Map();

components.set('BookYourDreamFlight', BookYourDreamFlight);
components.set('ChooseMeal', ChooseMeal);
components.set('CityBanner', CityBanner);
components.set('CityList', CityList);
components.set('ColumnSplitter', ColumnSplitter);
components.set('CommonHeadBanner', CommonHeadBanner);
components.set('Container', Container);
components.set('ContentBlock', ContentBlock);
components.set('CorporateTeam', CorporateTeam);
components.set('Departments', Departments);
components.set('ExperiencePageBanner', ExperiencePageBanner);
components.set('FAQs', FAQs);
components.set('FEaaSWrapper', FEaaSWrapper);
components.set('Footer', Footer);
components.set('FurtherInformationContact', FurtherInformationContact);
components.set('GetThereWithBeond', GetThereWithBeond);
components.set('Heading', Heading);
components.set('HomepageBanner', HomepageBanner);
components.set('HomepageDetails', HomepageDetails);
components.set('HomepageHotels', HomepageHotels);
components.set('HotelList', HotelList);
components.set('HowWeAreSustainable', HowWeAreSustainable);
components.set('Image', Image);
components.set('JourneyDetails', JourneyDetails);
components.set('JourneyDetailsSustainability', JourneyDetailsSustainability);
components.set('JourneyDetailsWhyBeond', JourneyDetailsWhyBeond);
components.set('LinkList', LinkList);
components.set('Locations', Locations);
components.set('ManagementTeam', ManagementTeam);
components.set('MyFamily', MyFamily);
components.set('Navigation', Navigation);
components.set('NeedToGetInTouch', NeedToGetInTouch);
components.set('NewsDetails', NewsDetails);
components.set('NewsList', NewsList);
components.set('PageContent', PageContent);
components.set('PartialDesignDynamicPlaceholder', PartialDesignDynamicPlaceholder);
components.set('PartnersList', PartnersList);
components.set('PrivacyAndPolicy', PrivacyAndPolicy);
components.set('Promo', Promo);
components.set('RichText', RichText);
components.set('RouteMap', RouteMap);
components.set('RowSplitter', RowSplitter);
components.set('Support', Support);
components.set('Sustainability', Sustainability);
components.set('Title', Title);
components.set('WayToTravel', WayToTravel);
components.set('AllBooking', AllBooking);
components.set('AllBookingDetails', AllBookingDetails);
components.set('ApiUrl', ApiUrl);
components.set('BoardingPasses', BoardingPasses);
components.set('BoardingPassesDetails', BoardingPassesDetails);
components.set('BookingComplete', BookingComplete);
components.set('CancelBooking', CancelBooking);
components.set('CancelSuccess', CancelSuccess);
components.set('ChangeDate', ChangeDate);
components.set('CheckIn', CheckIn);
components.set('ChooseSeats', ChooseSeats);
components.set('CompareFareFamilies', CompareFareFamilies);
components.set('CreateAccount', CreateAccount);
components.set('Debounce', Debounce);
components.set('EmergencyContactDetails', EmergencyContactDetails);
components.set('EmergenCycontactUser', EmergenCycontactUser);
components.set('FindBooking', FindBooking);
components.set('FlightAvailability', FlightAvailability);
components.set('Bliss', Bliss);
components.set('Delight', Delight);
components.set('FlightInfo', FlightInfo);
components.set('MatrixFunctions', MatrixFunctions);
components.set('Opulence', Opulence);
components.set('Header', Header);
components.set('LandingPageSearch', LandingPageSearch);
components.set('Layout', Layout);
components.set('CancelBookingLoader', CancelBookingLoader);
components.set('FindYourBooking', FindYourBooking);
components.set('GettingData', GettingData);
components.set('PaymentGateway', PaymentGateway);
components.set('SavingData', SavingData);
components.set('SavingExpLoader', SavingExpLoader);
components.set('SearchFlightLoader', SearchFlightLoader);
components.set('SearchSeat', SearchSeat);
components.set('SignInLoader', SignInLoader);
components.set('AdultAgeModal', AdultAgeModal);
components.set('CancelBookingModal', CancelBookingModal);
components.set('CookiesModal', CookiesModal);
components.set('DateOfBirthModal', DateOfBirthModal);
components.set('DepartReturnDateModal', DepartReturnDateModal);
components.set('DropdownModal', DropdownModal);
components.set('EmergencyExitSeatModal', EmergencyExitSeatModal);
components.set('FareBaggageModal', FareBaggageModal);
components.set('ModifyBookingDetailsModal', ModifyBookingDetailsModal);
components.set('ModifyBookingModal', ModifyBookingModal);
components.set('NoOptionFound', NoOptionFound);
components.set('PassengeRemoveModal', PassengeRemoveModal);
components.set('PassengerCount', PassengerCount);
components.set('PromoCodeModal', PromoCodeModal);
components.set('SelectSeatLaterModal', SelectSeatLaterModal);
components.set('YoungAgeModal', YoungAgeModal);
components.set('AnicillaryCodeForAddons', AnicillaryCodeForAddons);
components.set('FeaturedAddOns', FeaturedAddOns);
components.set('ModifyBooking', ModifyBooking);
components.set('MyFamilyDetails', MyFamilyDetails);
components.set('familyFields', familyFields);
components.set('MyProfile', MyProfile);
components.set('NoFlight', NoFlight);
components.set('CalculateDob', CalculateDob);
components.set('FieldsData', FieldsData);
components.set('PassengerDetails', PassengerDetails);
components.set('PaymentCancel', PaymentCancel);
components.set('PaymentProcess', PaymentProcess);
components.set('ReviewChange', ReviewChange);
components.set('CodesInCurve', CodesInCurve);
components.set('FlightSchedule', FlightSchedule);
components.set('GetDate', GetDate);
components.set('ModifyPassengerSeatFareFamily', ModifyPassengerSeatFareFamily);
components.set('PriceBreakDown', PriceBreakDown);
components.set('ReviewTrip', ReviewTrip);
components.set('ReviewTripComplete', ReviewTripComplete);
components.set('CountryData', CountryData);
components.set('SearchFlight', SearchFlight);
components.set('SitecoreContent', SitecoreContent);
components.set('StepsInfo', StepsInfo);
components.set('LandingPageOnewaySearchBar', LandingPageOnewaySearchBar);
components.set('LandingPageSearchBar', LandingPageSearchBar);
components.set('OnewayTab', OnewayTab);
components.set('ReturnTab', ReturnTab);
components.set('SelectOptions', SelectOptions);
components.set('SignIn', SignIn);
components.set('TermsConditions', TermsConditions);
components.set('ErrorMessages', ErrorMessages);
components.set('UpcomingTrip', UpcomingTrip);
components.set('YourCart', YourCart);

// Next.js 'dynamic' import and JavaScript 'dynamic' import are different.
// Next.js 'dynamic(...)' returns common 'React.ComponentType' while
// 'import('...')' returns 'Promise' that will resolve module.
// componentModule uses 'import(...)' because primary usage of it to get not only 'React Component' (default export) but all named exports.
// See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports
// componentFactory uses 'dynamic(...)' because primary usage of it to render 'React Component' (default export).
// See https://nextjs.org/docs/advanced-features/dynamic-import
// At the end you will have single preloaded script for each lazy loading module.
// Editing mode doesn't work well with dynamic components in nextjs: dynamic components are not displayed without refresh after a rendering is added. 
// This happens beacuse Sitecore editors simply insert updated HTML generated on server side. This conflicts with nextjs dynamic logic as no HTML gets rendered for dynamic component
// So we use require() to obtain dynamic components in editing mode while preserving dynamic logic for non-editing scenarios
// As we need to be able to seamlessly work with dynamic components in both editing and normal modes, different componentFactory functions will be passed to app

export function componentModule(componentName: string) {
  const component = components.get(componentName);

  // check that component is lazy loading module
  if (!component?.default && component?.module) {
    // return js dynamic import
    return component.module();
  }

  return component;
}

function baseComponentFactory(componentName: string, exportName?: string, isEditing?: boolean) {
  const DEFAULT_EXPORT_NAME = 'Default';
  const component = components.get(componentName);

  // check that component should be dynamically imported
  if (component?.element) {
    // return next.js dynamic import
    return component.element(isEditing);
  }

  if (exportName && exportName !== DEFAULT_EXPORT_NAME) {
    return component[exportName];
  }

  return component?.Default || component?.default || component;
}
  
export function componentFactory(componentName: string, exportName?: string) {
  return baseComponentFactory(componentName, exportName, false);
}

export function editingComponentFactory(componentName: string, exportName?: string) {
  return baseComponentFactory(componentName, exportName, true);
}
