/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || '{6AF17DD2-0FD7-4396-9869-2536E3B81876}',
config.sitecoreApiHost = process.env.SITECORE_API_HOST || 'https://xmc-arabesquefl0f70-demoproject-demoenv.sitecorecloud.io',
config.jssAppName = process.env.JSS_APP_NAME || 'flight-booking-sitecore',
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge',
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en',
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://xmc-arabesquefl0f70-demoproject-demoenv.sitecorecloud.io/sitecore/api/graph/edge',
module.exports = config;